backend/api/urls.py
from django.urls import path
from rest_framework import routers

from api import views

app_name = 'api'

urlpatterns = [
    path("login/", views.login_view, name="api_login"),
    path("logout/", views.logout_view, name="api_logout"),
    path("session/", views.session_view, name="api_session"),
    path("whoami/", views.whoami_view, name="api_whoami"),
    path("manual-login/", views.authenticate_view, name='login'),
    path('employees-list/', views.EmployeeView.as_view(), name='employees_list'),
    
    path('', views.index, name='index'),
]

router = routers.DefaultRouter()
router.register('employees', views.EmployeeViewSet, basename='employees')

urlpatterns += router.urls

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('api.urls')),
]

backend/api/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Employee(models.Model):
    DEPARTMENT_CHOICES = (
        ('hr', 'Human Resources'),
        ('finance', 'Finance'),
        ('engineering', 'Engineering'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='employees')
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES)
    salary = models.PositiveIntegerField()

backend/api/views.py
import json

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_POST

from api.models import Employee

# Create your views here.

def index(request):
    return render(request, "api/index.html")


# @method_decorator(login_required, name='dispatch')
class EmployeeView(TemplateView):
    # our hybrid template, shown above
    template_name = 'api/index.html'

    def get_context_data(self, **kwargs):
        # passing the department choices to the template in the context
        return {'department_choices': [{ 'id': c[0], 'name': c[1]} for c in Employee.DEPARTMENT_CHOICES],}
        
        
@require_POST
def login_view(request):
    data = json.loads(request.body)
    print("DATA", data)
    username = data.get('username')
    password = data.get('password')
    print("USERNAME and PASSWORD: ", username, password)
    if username is None or password is None:
        return JsonResponse({"details": "Please provide username and password"})
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return JsonResponse({"details": "Successfully logged in"})
    else:
        print("USER NOT FOUND")
        return JsonResponse({"details": "Invalid credentials"}, status=400)


def logout_view(request):
    if not request.user.is_authenticated:
        return JsonResponse({"details": "You are not logged in"}, status=400)
    logout(request)
    return JsonResponse({"details": "Successfully logged out"})


@ensure_csrf_cookie
def session_view(request):
    if not request.user.is_authenticated:
        return JsonResponse({"isauthenticated": False})
    return JsonResponse({"isauthenticated": True})


def whoami_view(request):
    if not request.user.is_authenticated:
        return JsonResponse({"isauthenticated": False})
    return JsonResponse({"username": request.user.username})

backend/templates/_base.html
{% load django_vite %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% vite_hmr_client %}
    {% vite_asset 'assets/style/style.css' %}
    <script type="module">
        import RefreshRuntime from 'http://localhost:5173/static/@react-refresh'
        RefreshRuntime.injectIntoGlobalHook(window)
        window.$RefreshReg$ = () => {}
        window.$RefreshSig$ = () => (type) => type
        window.__vite_plugin_react_preamble_installed__ = true
    </script>
</head>
<body class="m-4">
    {% if user.is_authenticated %}
        User is authenticated: <p class="text-md">{{ user.username }}</p>
    {% endif %}
    <a href="{% url 'api:index' %}">index</a>
    {% block content %}
    {% endblock content %}
    {% vite_asset 'assets/main.jsx' %}
    {% vite_asset 'assets/index.js' %}
</body>
</html>

backend/templates/api/index.html
{% extends "_base.html" %}

{% block content %}
    <h3>Api Index</h3>
    <div id="root"></div>
    <div>
        <a href="{% url 'api:employees_list' %}">Employees List -></a>
        {% if department_choices %}
            <h3 class="text-green-400">Department Choices EXIST</h3>
            {{ department_choices|json_script:'department-choices-id'}}
            <h6 class="text-xs">They have been loaded in browser console.</h6>
            <script>
                const DEPARTMENT_CHOICES = JSON.parse(document.getElementById('department-choices-id').textContent);
                console.log(DEPARTMENT_CHOICES);
                // department_choices now is available for javascript, we can process it
            </script>
        {% else %}
            <h3 class="text-red-400">Department Choices DO NOT EXIST</h3>
        {% endif %}
    </div>
{% endblock content %}

backend/templates/index.html
{% extends "_base.html" %}

{% block content %}
{% endblock content %}